/* xkeycaps, Copyright (c) 1997 Jamie Zawinski <jwz@jwz.org>
 *
 * This file describes keycodes generated by the Midwest-Micro
 * Elite Soundbook multimedia notebook keyboard interface.
 * By Garst R. Reese <reese@isn.net>
 */

static const KeyCode elite_codes [] = {
 /* Row 0 */
 9, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 95, 96, 77, 111, 78, 110,

 /* Row 2 */
 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 97,

 /* Row 3 */
 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 51, 99,

 /* Row 4 */
 66, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 36, 105,

 /* Row 5 */
 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 98, 103,

 /* Row 6 */
 0, 37, 64, 49, 65, 113, 106, 107, 100, 104, 102
};

