/* xkeycaps, Copyright (c) 1994, 1995, 1996 Jamie Zawinski <jwz@jwz.org>
 *
 * This file describes keycodes generated by the Texas Instruments
 * TravelMate 4000M multimedia notebook keyboard interface.
 * By Kenneth E. Harker <iago@cs.dartmouth.edu>
 */

static const KeyCode tm4000m_codes [] = {
 /* Row 0 */
 9, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 95, 96, 78, 111, 110, 106, 107,

 /* Row 2 */
 49, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,

 /* Row 3 */
 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 51,

 /* Row 4 */
 66, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 36,

 /* Row 5 */
 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,

 /* Row 6a */
 0, 37, 64, 65, 113, 97, 98, 103, 99,

 /* Row 6b */
 100, 104, 102, 105

};

