/* xkeycaps, Copyright (c) 1994 Jamie Zawinski <jwz@jwz.org>
 *
 * This file describes keycodes generated by the Takaoka Xmint X Terminal.
 * By Christian Goetze <c-goetze@u-aizu.ac.jp>
 */

static const KeyCode xmint_codes [] = {
 /* Row 0 */
 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 21,

 /* Row 2 */
 20, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,

 /* Row 3 */
 11, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 22,

 /* Row 4 */
 10, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 23,

 /* Row 5 */
  8, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,  9, 18,

 /* Row 6 */
 16, 14, 12, 19, 13, 15, 17
};
